### ISSUE TITLE
ispeech-asr.agi always return error unless replay recorded speech is enabled

### ISSUE THREAD

**Issue by thorzh** [zaf/asterisk-ispeech#1]
The AGI always return error 

-- ispeech-asr.agi: An iSpeech API error occured: result=error&code=24&message=Bad+audio+data

However, if replay recorded speech is enabled, it normally works fine.

**Comment by zaf** [comment]
Hello,

it seems to randomly happen when SSL is not used. I'm not sure why but with SSL on ASR works reliably. I have pushed an update that enables SSL use by default and that seems to deal with the issue.

**Comment by thorzh** [comment]
It doesn't make a difference for me whether SSL is enabled or not.  However, it does work by adding a 0.5s delay before encoding the sound.

**Comment by zaf** [comment]
That is quite interesting. I can only guess it has something to do with the recorded files not being synced on the filesystem before being read by the script. What version of asterisk are you using and do you have any options like 'cache_record_files' in asterisk.conf enabled? What is your filesystem and the storage hardware?
Since i can't seem to be able to reproduce it here can you try instead of the delay to add a call to sync and see what the results are?

**Comment by thorzh** [comment]
You're right, it's the  'cache_record_files'.  Once that's disabled, it works fine now.  Thanks.
